apiVersion: v1
kind: ConfigMap
metadata:
  name: &app-name go-rest-balance-charges-cm
  namespace: test-a
  labels:
    app: *app-name
data:
  PORT: "8901"
  POD_NAME: "go-rest-balance-charges"
  API_VERSION: "1.0"
  DB_HOST: "db-arch.couoacqalfwt.us-east-2.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_NAME: "postgres"
  DB_SCHEMA: "public"
  SERVER_URL_DOMAIN: "http://svc-go-rest-balance.test-a.svc.cluster.local:8900"
  NO_AZ: "true"
  REDIS_ADDRESS: "redis-arch-vovqz2.serverless.use2.cache.amazonaws.com:6379"
  REDIS_CLUSTER_ADDRESS: "clustercfg.memdb-arch.vovqz2.memorydb.us-east-2.amazonaws.com:6379"
  REDIS_DB_NAME: "0"
  REDIS_PASSWORD: ""